pipeline {
  agent any

  stages {

    stage('Info') {
      steps {
        sh 'echo "Job: ${JOB_NAME}"'
        sh 'echo "Build: ${BUILD_NUMBER}"'
      }
    }



    stage('Lint') {
      agent {
        docker {
          image 'python:3.6-slim'
        }
      }
      steps {
        sh '''
          apt-get update && apt-get install -y make python3-venv
          python3 -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install black flake8 mypy
          # Fix formatting before checking
          make reformat
          make lint
        '''
      }
    }

    stage('Test') {
      agent {
        docker {
          image 'python:3.6-slim'
        }
      }
      steps {
        sh '''
          apt-get update && apt-get install -y make python3-venv
          python3 -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install pytest coverage
          make test
        '''
      }
    }

   

  }
}